name       : shadow
version    : '4.14.1'
release    : 24
source     :
    - https://github.com/shadow-maint/shadow/releases/download/4.14.1/shadow-4.14.1.tar.xz : 0141b283da9a0cd70128e9c083f1c64062686385ddaf5e64ca28de802e37e5d1
license    : BSD-3-Clause
component  : system.base
summary    : login and password tools
description: |
    Utilities for managing shadow password files and user/group accounts
builddeps  :
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - pkgconfig(libeconf)
    - pkgconfig(libxcrypt)
setup      : |
    %patch -p1 -i $pkgfiles/0001-Adapt-login.defs-for-PAM-and-util-linux.patch
    %patch -p1 -i $pkgfiles/0002-Solus-login.defs-changes.patch

    # add extra check, preventing accidental deletion of other user's home dirs when using `userdel -r <user with home in />`
    export CFLAGS="$CFLAGS -DEXTRA_CHECK_HOME_DIR"
    %configure \
               --disable-account-tools-setuid \
               --enable-man \
               --enable-vendordir=/usr/share/defaults/etc/ \
               --with-fcaps \
               --with-libpam \
               --with-yescrypt \
               --without-libbsd \
               --without-nscd \
               --without-su
build      : |
    %make
install    : |
    %make_install
    make DESTDIR="$installdir" -C man install

    # Get rid of groups
    find $installdir/usr/share/man -type f -name "groups.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/groups

    # Get rid of faillog (Not used)
    find $installdir/usr/share/man -type f -name "faillog.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/faillog

    # Get rid of logoutd (Not used)
    find $installdir/usr/share/man -type f -name "logoutd.*" | xargs rm -frv
    rm -fv $installdir/usr/sbin/logoutd

    # Get rid of chfn (util-linux)
    find $installdir/usr/share/man -type f -name "chfn.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/chfn

    # Get rid of chsh (util-linux)
    find $installdir/usr/share/man -type f -name "chsh.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/chsh

    # Get rid of login (util-linux)
    find $installdir/usr/share/man -type f -name "login.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/login

    # Get rid of newgrp (util-linux)
    find $installdir/usr/share/man -type f -name "newgrp.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/newgrp

    # Get rid of nologin (util-linux)
    find $installdir/usr/share/man -type f -name "nologin.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/nologin

    # Get rid of vigr (util-linux)
    find $installdir/usr/share/man -type f -name "vigr.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/vigr

    # Get rid of vipr (util-linux)
    find $installdir/usr/share/man -type f -name "vipr.*" | xargs rm -frv
    rm -fv $installdir/usr/bin/vipr

    # Set up stateless support for pam.d
    rm -rf $installdir/etc/pam.d
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    install -m00644 $pkgfiles/pam.d/* -t $installdir/usr/share/defaults/etc/pam.d

    # Login.defs
    install -Dm00644 $installdir/etc/login.defs $installdir/usr/share/defaults/etc/login.defs
    rm -v $installdir/etc/login.defs
    rmdir $installdir/etc

    # Install compat links T10615
    for TOP in {bin,sbin}; do
        install -D -d -m 00755 $installdir/$TOP
        pushd $installdir/usr/$TOP
        for FILE in *; do
            ln -sv /usr/$TOP/$FILE $installdir/$TOP/$FILE
        done
        popd
    done

## TODO:
# - Stateless /etc/skel
